language: r
sudo: false
cache: packages

r:
 - release
 - devel
 - oldrel

addons:
  apt:
    packages:
      - libsecret-1-dev

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'
