language: r
dist: trusty
sudo: false
cache: packages

os:
  - linux
  - osx

r:
 - release
 - devel
 - oldrel

addons:
  apt:
    sources:
      - sourceline: 'ppa:chris-lea/libsodium'
    packages:
      - libsecret-1-dev
      - libsodium-dev

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'
